os: linux
language: generic


services:
  - docker

before_install:
  - docker build --tag mikalaihryb/frontend --file docker/frontend/Dockerfile.dev .

script:
  - docker run --env CI=true mikalaihryb/frontend npm run test
