os: linux
language: generic


services:
  - docker

before_install:
  - docker build --tag mikalaihryb/frontend --file ./docker/frontend/Dockerfile.dev ./docker/frontend

script:
  - docker run --env CI=true mikalaihryb/frontend npm run test
