sudo: required
language: generic

services:
  - docker

before_install:
  - docker build --tag mikalaihryb/frontend --file Dockerfile.dev .

script:
  - docker run --env CI=true mikalaihryb/frontend npm run test
